# .github/workflows/release-noupx.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary without Compression
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [freebsd,windows]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: 386
            goos: windows
          - goarch: amd64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "golerta-cli"
        pre_command: export CGO_ENABLED=0
        ldflags: "-s -w"
